### ISSUE TITLE
still getting TypeError: parser is not a constructor

### ISSUE THREAD

**Issue by RaviPabari** [1623311678/html-parser-server#1]
Am I missing something here?

**Comment by 1623311678** [comment]
hi，if you are use commonjs you can  resolve issue as follow:
const parser =require('parser-html-json').default
if you are use esmodule you can resolve issue as follow:
import parser from 'parser-html-json'
const htmlParser = new parser.default(html)

**Comment by 1623311678** [comment]
> hi，if you are use commonjs you can resolve issue as follow:
> const parser =require('parser-html-json').default
> if you are use esmodule you can resolve issue as follow:
> import parser from 'parser-html-json'
> const htmlParser = new parser.default(html)

**Comment by 1623311678** [comment]
> Am I missing something here?

hi，I am here .if you use commonjs you can resolve this issue as follow:
const parser =require('parser-html-json').default
const htmlParser = new parser(html)
if you  use esModule you can resolve this issue as follow:
import parser from 'parser-html-json'
const htmlParser = new parser.default(html)

**Comment by 1623311678** [comment]
> Am I missing something here?

I am sorry for this issue ,maybe some rules has changed

**Comment by RaviPabari** [comment]
> > Am I missing something here?
> 
> hi，I am here .if you use commonjs you can resolve this issue as follow: const parser =require('parser-html-json').default const htmlParser = new parser(html) if you use esModule you can resolve this issue as follow: import parser from 'parser-html-json' const htmlParser = new parser.default(html)

Sorry for late reply, I tried using the (dot) default but then the html I pass to the parser object returns empty array

**Comment by 1623311678** [comment]
> > > Am I missing something here?
> > 
> > 
> > hi，I am here .if you use commonjs you can resolve this issue as follow: const parser =require('parser-html-json').default const htmlParser = new parser(html) if you use esModule you can resolve this issue as follow: import parser from 'parser-html-json' const htmlParser = new parser.default(html)
> 
> Sorry for late reply, I tried using the (dot) default but then the html I pass to the parser object returns empty array

you html string must have one body tag ,for example :`<body><div>111</div></body>`you can copy my demo and test

**Comment by RaviPabari** [comment]
Ok I'll try that

**Comment by RaviPabari** [comment]
Still didn't worked for me, thanks for the help closing the issue now.
