### ISSUE TITLE
crash in ts

### ISSUE THREAD

**Issue by Mrliwang** [1623311678/html-parser-server#2]
crash with this error，what  happened?

Error type:TypeError
Error message:Constructor is false
SourceCode:
        let parserJson = new ParserHTMLJson(html);

**Comment by 1623311678** [comment]
try new ParserHTMLJSON.default(html)


the html has contain body tag



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 17, 2024 18:10 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [1623311678/html-parser-server] crash in ts (Issue #2)




 
crash with this error，what  happened?
 
Error type:TypeError
 Error message:Constructor is false
 SourceCode:
 let parserJson = new ParserHTMLJson(html);

**Comment by 1623311678** [comment]
https://github.com/1623311678/html-parser-server/issues/1


please reference this closed issue


my node version is 14 use that solution ,I can get json from html



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 17, 2024 18:10 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [1623311678/html-parser-server] crash in ts (Issue #2)




 
crash with this error，what  happened?
 
Error type:TypeError
 Error message:Constructor is false
 SourceCode:
 let parserJson = new ParserHTMLJson(html);

**Comment by Mrliwang** [comment]
the index.d.ts is only export the htmlParser class, and it don't have a propety 'default'

and the ide will tips error with [Property 'default' does not exist on type 'typeof htmlParser'.]

it can work?

**Comment by 1623311678** [comment]
> the index.d.ts is only export the htmlParser class, and it don't have a propety 'default'
> 
> and the ide will tips error with [Property 'default' does not exist on type 'typeof htmlParser'.]
> 
> it can work?

yes , the following is demo 

node index.js or node index.ts can get output

const parser =  require('parser-html-json').default
const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    .tagh1{
        background-color: aquamarine;
        color:'blue';
    }
    .one-div{
        line-height: 30px;
    }
</style>
<body>
    <h1 class="tagh1">
        kkkk
        <p>hhhhh</p>
    </h1>
    <div style="color:red; height:100px;" class="one-div">cshi</div>
    <img src="https:baidu.com" alt="wwww"/>
    <p>wjdwekfe>>>>></p>
    <em>dsjfw<<<<<p
    <div>dksfmjk</div>
    owqkdo</em>
</body>
</html>
`
const htmlParser = new parser(html)
const dom = htmlParser.getHtmlJson()

const css = htmlParser.getClassStyleJson()
console.log('123',dom,css)

**Comment by 1623311678** [comment]
> the index.d.ts is only export the htmlParser class, and it don't have a propety 'default'
> 
> and the ide will tips error with [Property 'default' does not exist on type 'typeof htmlParser'.]
> 
> it can work?

you can use this demo:
const parser =  require('parser-html-json').default
const html = ''
const htmlParser = new parser(html)
const dom = htmlParser.getHtmlJson()

const css = htmlParser.getClassStyleJson()
console.log('123',dom,css)
<img width="1658" alt="image" src="https://github.com/1623311678/html-parser-server/assets/41052302/0571e686-12d6-4d6a-b942-c2c647f50d0c">

I try it , in index.js or index.ts 

then use node index.js or node index.ts , it can get output
<img width="863" alt="image" src="https://github.com/1623311678/html-parser-server/assets/41052302/a23c9fb2-30cd-48e3-9897-4998ee632247">

Finally, default is not the code itself, but the packaging is faulty, so use it as needed

const parser =  require('parser-html-json').default

**Comment by 1623311678** [comment]
> the index.d.ts is only export the htmlParser class, and it don't have a propety 'default'
> 
> and the ide will tips error with [Property 'default' does not exist on type 'typeof htmlParser'.]
> 
> it can work?

I have update the demo code,you can copy and try it

I tried in js and ts ,it can ouput successfully ,but I use node index.js or node index.ts

<img width="1011" alt="image" src="https://github.com/1623311678/html-parser-server/assets/41052302/9a3e026b-f26d-4e53-b759-fd3a41af91e7">

**Comment by Mrliwang** [comment]
node index.js or node index.ts is can work
thank you very much!
